import ThemeRegistry from "@/components/ThemeRegistery";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next App MUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
